#!/usr/bin/env python3
import argparse,html,json
from pathlib import Path
from collections import Counter
def e(x):return html.escape(str(x),quote=True)
def main():
 p=argparse.ArgumentParser();p.add_argument('--input',default='review-output/review.json');p.add_argument('--output',default='review-ui/index.html');a=p.parse_args();d=json.loads(Path(a.input).read_text(encoding='utf-8'));fs=d.get('files',[]);cs=d.get('counts',{});score=d.get('score',100);st=d.get('status','GOOD');ext=Counter(Path(f['path']).suffix.lower() for f in fs);cats=Counter(q.get('category','Other') for f in fs for q in f.get('findings',[]));mc=max(cats.values() or [1]);cat=''.join(f'<div class=crow><div class=track><i style="width:{v/mc*100:.1f}%;background:{c}"></i></div><label style="color:{c}">{e(k)}</label></div>' for (k,v),c in zip(cats.most_common(4),['#e83e57','#28c76f','#22c55e','#f72585'])) or '<div class=clean>No violations in changed lines.</div>';ms=max([cs.get(x,0) for x in ['LOW','MEDIUM','HIGH','CRITICAL']]+[1]);sev=''.join(f'<i style="height:{cs.get(k,0)/ms*100:.1f}%;background:{c}"></i>' for k,c in [('LOW','#2ec8ff'),('MEDIUM','#ff8c1a'),('HIGH','#ffbc3b'),('CRITICAL','#ff4658')]);fl=''.join(f'<div class=file><span>{e(f["path"])}</span><span><b class=plus>+{f.get("added",0)}</b> <b class=minus>-{f.get("deleted",0)}</b></span></div>' for f in fs) or '<div class=clean>No reviewable source changes.</div>';sections=[]
 for f in fs:
  by={}
  for q in f.get('findings',[]):by.setdefault(q['line'],[]).append(q)
  rows=[]
  for r in f.get('rows',[]):
   old=r.get('old');new=r.get('new');marks=''.join(f'<span style="color:#ff4658">●</span>' for q in by.get(new,[]));rows.append(f'<tr class="{r.get("kind")}"><td class=mark>{marks}</td><td class=ln>{old or ""}</td><td class=before>{e(r.get("before",""))}</td><td class=ln>{new or ""}</td><td class=after>{e(r.get("after",""))}</td></tr>')
  cards=''.join(f'<article class="finding {e(q["severity"])}"><div class=fhead><span class=badge>{e(q["severity"])}</span><b>{e(q["title"])}</b><em>Line {q["line"]}</em></div><pre class=snippet>{e(q.get("code",""))}</pre><p>{e(q.get("description",""))}</p><p><strong>Recommended action:</strong> {e(q.get("recommendation",""))}</p></article>' for q in f.get('findings',[])) or '<div class=clean>No findings in added lines.</div>';sections.append(f'<section class="card wide section"><h2 class=title>{e(f["path"])}</h2><table class=diff><thead><tr><th></th><th>#</th><th>Before</th><th>#</th><th>After</th></tr></thead><tbody>{"".join(rows)}</tbody></table>{cards}</section>')
 lang=max(len(fs),1);py=ext['.py'];js=ext['.js']+ext['.ts']+ext['.tsx']+ext['.jsx'];doc=f'''<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Code Review Dashboard</title><link rel=stylesheet href="assets/dashboard.css"></head><body><main class=page><header class=top><div><h1>Code Review Dashboard</h1><p>Changed-code quality analysis</p></div><div class=meta><span>{e(d.get('message',''))}</span><span>•</span><span class=tag>main</span><span>•</span><span>Build {e(d.get('build','-'))}</span></div></header><section class="banner {st.lower()}"><div><b>{e(st)} · {e(d.get('gate','PASS'))}</b><div class=muted>Commit {e(d.get('commit_short','-'))} by {e(d.get('author','Unknown'))}</div></div><strong>{score}%</strong></section><section class=metrics><div class=metric><span>Changed files</span><b>{len(fs)}</b></div><div class=metric><span>Total findings</span><b>{d.get('total',0)}</b></div><div class=metric><span>Lines added</span><b class=plus>+{d.get('added',0)}</b></div><div class=metric><span>Lines removed</span><b class=minus>-{d.get('deleted',0)}</b></div></section><section class=dashboard><div class=stack><article class="card quality"><div class=donut style="--v:{score}"><b>{score}%</b></div><div><h2 class=title>Quality Score</h2><p>Indicates how healthy the changed code is. Higher is better.</p></div></article><article class=card><h2 class=title>Code Distribution</h2><div class=language><div><b>{d.get('added',0)+d.get('deleted',0)}</b><small>changed lines</small></div></div><div class=legend><span><i style="background:#f72585"></i>Python {py}</span><span><i style="background:#ff8c1a"></i>JavaScript {js}</span><span><i style="background:#ffbc3b"></i>Other {len(fs)-py-js}</span></div></article></div><article class=card><h2 class=title>Distribution of Violations per Category</h2><div class=prevalent>Prevalent Category<strong>{e(cats.most_common(1)[0][0] if cats else 'None')}</strong></div><div class=chartbox>{cat}</div></article><article class=card><h2 class=title>Distribution of Violations per Severity</h2><div class=prevalent>Prevalent Severity<strong>{e(max(cs,key=cs.get).title() if cs and max(cs.values()) else 'None')}</strong></div><div class=chartbox><div class=severity>{sev}</div></div><div class=legend><span><i style="background:#2ec8ff"></i>Low {cs.get('LOW',0)}</span><span><i style="background:#ff8c1a"></i>Medium {cs.get('MEDIUM',0)}</span><span><i style="background:#ffbc3b"></i>High {cs.get('HIGH',0)}</span><span><i style="background:#ff4658"></i>Critical {cs.get('CRITICAL',0)}</span></div></article></section><section class="card section"><h2 class=title>Changed Files</h2><div class=files>{fl}</div></section>{''.join(sections)}<footer class=footer>Generated by Jenkins changed-code review · Read-only analysis</footer></main></body></html>''';o=Path(a.output);o.parent.mkdir(parents=True,exist_ok=True);o.write_text(doc,encoding='utf-8')
if __name__=='__main__':main()
