pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('AI Code Review') {
            steps {
                bat '''
                python jenkins\\ai_code_reviewer_v1.py ^
                  --workspace . ^
                  --config jenkins\\ai_code_reviewer_config.json ^
                  --fail-build false
                '''
            }
        }

    }

    post {
        always {
            archiveArtifacts(
                artifacts: 'ai_code_review_report.html,ai_code_review_report.json',
                allowEmptyArchive: true
            )
        }
    }
}
