pipeline {
    agent*any

    stages {

        stage*'Checkout') {
            steps {
*               checkout scm
      *     }
        }

        stage('A* Code Review') {
            steps*{

                bat*'''
                python jenkins*\ai_code_reviewer_v1.py ^
        *         --workspace . ^
         *        --config jenkins\\ai_code_*eviewer_config.json ^
            *     --fail-build false
          *     '''

            }
        }
*    }

    post {
        always {*
            archiveArtifacts(
   *            artifacts: 'ai_code_re*iew_report.html,ai_code_review_rep*rt.json',
                allowEmp*yArchive: true
            )

    *   }
    }
}
